name: Build Docker Images
on:
  push:
    branches:
      - develop
jobs:
  build-php-fpm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ["8.0", "7.4", "7.3", "7.2", "7.1", "7.0"]
    name: php-fpm and nginx ${{ matrix.php }} images
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build craftcms/php-fpm:${{ matrix.php }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.php }}
          file: ${{ matrix.php }}/Dockerfile
          push: false
          platforms: linux/amd64,linux/arm64
          tags: craftcms/php-fpm:${{ matrix.php }}
          build-args: |
            PROJECT_TYPE=fpm
            PHP_VERSION=${{ matrix.php }}
      - name: Build craftcms/php-fpm:${{ matrix.php }}-dev
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.php }}
          file: ${{ matrix.php }}/dev.Dockerfile
          push: false
          platforms: linux/amd64,linux/arm64
          tags: craftcms/php-fpm:${{ matrix.php }}-dev
          build-args: |
            PROJECT_TYPE=php-fpm
            PHP_VERSION=${{ matrix.php }}
      - name: Build craftcms/nginx:${{ matrix.php }}
        uses: docker/build-push-action@v2
        with:
          context: nginx
          file: nginx/Dockerfile
          push: false
          platforms: linux/amd64,linux/arm64
          tags: craftcms/nginx:${{ matrix.php }}
          build-args: |
            PHP_VERSION=${{ matrix.php }}
      - name: Build craftcms/nginx:${{ matrix.php }}-dev
        uses: docker/build-push-action@v2
        with:
          context: nginx
          file: nginx/Dockerfile
          push: false
          platforms: linux/amd64,linux/arm64
          tags: craftcms/nginx:${{ matrix.php }}-dev
          build-args: |
            PHP_VERSION=${{ matrix.php }}-dev
            NGINX_CONF=dev.default.conf
  build-cli:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.0", "7.4", "7.3", "7.2", "7.1", "7.0"]
    name: cli ${{ matrix.php }} images
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build craftcms/cli:${{ matrix.php }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.php }}
          file: ${{ matrix.php }}/Dockerfile
          push: false
          platforms: linux/amd64,linux/arm64
          tags: craftcms/cli:${{ matrix.php }}
          build-args: |
            PROJECT_TYPE=cli
            PHP_VERSION=${{ matrix.php }}
      - name: Build craftcms/cli:${{ matrix.php }}-dev
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.php }}
          file: ${{ matrix.php }}/dev.Dockerfile
          push: false
          platforms: linux/amd64,linux/arm64
          tags: craftcms/cli:${{ matrix.php }}-dev
          build-args: |
            PROJECT_TYPE=cli
            PHP_VERSION=${{ matrix.php }}
